version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    groups:
       updates:
          patterns:
            - "*"
    rebase-strategy: "auto"
    labels:
      - "security"
      - "dependencies"

  - package-ecosystem: "terraform"
    directory: "infra/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    groups:
       updates:
          patterns:
            - "*"
    rebase-strategy: "auto"
    labels:
      - "security"
      - "dependencies"

